services:
  postgres:
    image: postgres:18-alpine
    container_name: helpdesk-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - helpdesk-network

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: helpdesk-keycloak
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${KC_HOSTNAME_PORT}:${KC_HOSTNAME_PORT}"
    networks:
      - helpdesk-network

  api:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: helpdesk-api
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - helpdesk-network

  web:
    build:
      dockerfile: ./web/Dockerfile
    container_name: helpdesk-web
    depends_on:
      api:
        condition: service_started
    ports:
      - "5173:80"
    networks:
      - helpdesk-network

volumes:
  postgres_data:

networks:
  helpdesk-network:
    driver: bridge
