#!/bin/bash
set -e

# Create keycloak database and user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $KC_DB_USERNAME WITH PASSWORD '$KC_DB_PASSWORD';
    CREATE DATABASE $KC_DATABASE OWNER $KC_DB_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE $KC_DATABASE TO $KC_DB_USERNAME;
EOSQL

# Create auth_platform database and user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $SPRING_DATASOURCE_USERNAME WITH PASSWORD '$SPRING_DATASOURCE_PASSWORD';
    CREATE DATABASE $SPRING_DATASOURCE_DB OWNER $SPRING_DATASOURCE_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE $SPRING_DATASOURCE_DB TO $SPRING_DATASOURCE_USERNAME;
EOSQL
